import React, { useState } from 'react';
import { ShieldCheck, Mail, Lock, User, X, Sparkles, Loader2, AlertCircle, Eye, EyeOff, Check } from 'lucide-react';
import { loginUser, signupUser } from '../api/client';

export default function AuthModal({ isOpen, onClose, onAuthSuccess }) {
  const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [role, setRole] = useState('analyst'); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [showPassword, setShowPassword] = useState(false);
  if (!isOpen) return null;
  const passwordReady = password.length >= 8;
  const handleSubmit = async (e) => { e.preventDefault(); setError(''); if (!email || !password) return setError('Enter your email and password to continue.'); if (mode === 'signup' && !fullName.trim()) return setError('Add your full name or investigator callsign.'); setLoading(true); try { const data = mode === 'login' ? await loginUser(email, password) : await signupUser(email, password, fullName, role); onAuthSuccess(data); onClose(); } catch (err) { setError(err.message || 'Authentication failed. Please check your credentials.'); } finally { setLoading(false); } };
  const fillDemoCreds = (type) => { setMode('login'); setError(''); setEmail(type === 'analyst' ? 'analyst@threatlens.io' : 'admin@threatlens.io'); setPassword(type === 'analyst' ? 'threatlens2026' : 'admin2026'); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/75 backdrop-blur-md reveal" role="dialog" aria-modal="true" aria-labelledby="auth-title"><div className="glass glass-strong relative w-full max-w-md rounded-3xl p-6 sm:p-8 shadow-2xl">
    <button type="button" onClick={onClose} aria-label="Close authentication dialog" className="absolute top-4 right-4 p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/10"><X className="w-5 h-5" /></button>
    <div className="flex items-center gap-3 mb-6"><div className="bg-accent shadow-accent p-3 rounded-2xl text-slate-950"><ShieldCheck className="w-6 h-6" /></div><div><h2 id="auth-title" className="text-lg font-black">{mode === 'login' ? 'Welcome back, analyst' : 'Create investigator access'}</h2><p className="text-xs text-slate-400">{mode === 'login' ? 'Access forensic audits and evidence records.' : 'Register your identity in the Evidence Vault.'}</p></div></div>
    <div className="mb-5 p-3 rounded-2xl bg-slate-950/45 border border-white/10"><div className="flex items-center gap-2 text-[11px] font-bold text-slate-300 mb-2"><Sparkles className="w-3.5 h-3.5 text-amber-300" />QUICK DEMO ACCESS</div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => fillDemoCreds('analyst')} className="text-left p-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-[11px]"><b className="text-accent">Analyst</b><span className="block text-slate-400 font-mono">analyst@threatlens.io</span></button><button type="button" onClick={() => fillDemoCreds('admin')} className="text-left p-2 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-[11px]"><b className="text-emerald-300">Admin</b><span className="block text-slate-400 font-mono">admin@threatlens.io</span></button></div></div>
    <div className="flex gap-1 p-1 mb-5 rounded-xl bg-slate-950/60 border border-white/10"><button type="button" onClick={() => { setMode('login'); setError(''); }} className={`flex-1 py-2 rounded-lg text-xs font-bold ${mode === 'login' ? 'bg-accent text-slate-950' : 'text-slate-400'}`}>Sign in</button><button type="button" onClick={() => { setMode('signup'); setError(''); }} className={`flex-1 py-2 rounded-lg text-xs font-bold ${mode === 'signup' ? 'bg-accent text-slate-950' : 'text-slate-400'}`}>Create account</button></div>
    <form onSubmit={handleSubmit} className="space-y-4">{mode === 'signup' && <Field icon={User} label="Full name / callsign"><input required value={fullName} onChange={e => setFullName(e.target.value)} placeholder="Inspector Ananya Roy" className="auth-input pl-10" /></Field>}<Field icon={Mail} label="Email address"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="analyst@threatlens.io" className="auth-input pl-10 font-mono" /></Field><Field icon={Lock} label="Password"><div className="relative"><input required type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter secure password" className="auth-input pl-10 pr-11 font-mono" /><button type="button" onClick={() => setShowPassword(v => !v)} aria-label={showPassword ? 'Hide password' : 'Show password'} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-slate-400 hover:text-accent">{showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button></div></Field>{mode === 'signup' && <><div className={`flex items-center gap-2 text-[11px] ${passwordReady ? 'text-emerald-300' : 'text-slate-500'}`}><Check className="w-3.5 h-3.5" />Use at least 8 characters</div><select value={role} onChange={e => setRole(e.target.value)} className="auth-input"><option value="analyst">Cyber Cell Analyst</option><option value="admin">Enterprise Lead / CERT-In Admin</option></select></>}{error && <div className="flex gap-2 p-3 rounded-xl bg-rose-400/10 border border-rose-400/25 text-rose-300 text-xs"><AlertCircle className="w-4 h-4 shrink-0" />{error}</div>}<button type="submit" disabled={loading} className="w-full py-3 rounded-xl bg-accent text-slate-950 text-xs font-black shadow-accent hover:brightness-110 disabled:opacity-50">{loading ? <span className="flex justify-center gap-2"><Loader2 className="w-4 h-4 animate-spin" />Securing session...</span> : mode === 'login' ? 'Enter secure console' : 'Complete registration'}</button></form>
  </div></div>;
}
function Field({ icon: Icon, label, children }) { return <label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">{label}</span><div className="relative"><Icon className="absolute left-3 top-3 w-4 h-4 text-slate-500" />{children}</div></label>; }
