import React, { useEffect, useState } from 'react';
import { Sliders, Trash2, CheckCircle2, Lock, EyeOff, Palette, Check } from 'lucide-react';
import { getSettings, updateRetention } from '../api/client';

export default function SettingsModal({ maskPii, setMaskPii, accentTheme, setAccentTheme }) {
  const [retentionDays, setRetentionDays] = useState(90); const [loading, setLoading] = useState(false); const [purgeResult, setPurgeResult] = useState(null);
  useEffect(() => { getSettings().then(data => { if (data.retention_days) setRetentionDays(data.retention_days); }).catch(e => console.error(e)); }, []);
  const handleUpdateRetention = async () => { setLoading(true); setPurgeResult(null); try { const res = await updateRetention(retentionDays); setPurgeResult(res.purge_result); } catch (err) { alert('Retention update failed: ' + err.message); } finally { setLoading(false); } };
  const themes = [{ id: 'teal', label: 'Signal teal', color: '#17c3c5' }, { id: 'indigo', label: 'Command indigo', color: '#6366f1' }, { id: 'rose', label: 'Alert rose', color: '#f43f6e' }, { id: 'emerald', label: 'Secure emerald', color: '#10b981' }, { id: 'amber', label: 'Caution amber', color: '#f5a524' }, { id: 'sky', label: 'Recon sky', color: '#0ea5e9' }];
  return <div className="glass max-w-3xl mx-auto rounded-3xl p-6 sm:p-8 shadow-xl space-y-6 reveal"><div className="pb-5 border-b border-white/10"><h2 className="text-lg font-black flex items-center gap-2"><Sliders className="w-5 h-5 text-accent" />Governance, retention & masking</h2><p className="text-xs text-slate-400 mt-1">Configure the Evidence Vault and tune the console to your operational preference.</p></div>
    <section className="glass-strong hover-lift p-5 rounded-2xl space-y-4"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div><h3 className="text-sm font-bold flex items-center gap-2"><Trash2 className="w-4 h-4 text-amber-300" />Raw email retention window</h3><p className="text-xs text-slate-400 mt-1 leading-5">Raw MIME bodies are purged after this period while hashes, metadata, and the Evidence Vault chain survive indefinitely.</p></div><div className="flex items-center gap-2"><input type="number" min="1" max="365" value={retentionDays} onChange={e => setRetentionDays(parseInt(e.target.value) || 30)} className="auth-input w-20 font-mono" /><span className="text-xs text-slate-400">days</span></div></div><button type="button" onClick={handleUpdateRetention} disabled={loading} className="px-4 py-2 rounded-xl bg-white/10 hover:bg-white/15 text-xs font-semibold border border-white/10">{loading ? 'Applying...' : 'Apply policy & trigger purge daemon'}</button>{purgeResult && <div className="p-3 rounded-xl bg-emerald-400/10 border border-emerald-400/25 text-emerald-300 text-xs flex gap-2"><CheckCircle2 className="w-4 h-4" />Purge executed: {purgeResult.purged_count} records sanitized. Proof hashes retained.</div>}</section>
    <section className="glass-strong p-5 rounded-2xl space-y-4"><h3 className="text-sm font-bold flex items-center gap-2"><Palette className="w-4 h-4 text-accent" />Console accent color</h3><p className="text-xs text-slate-400">Choose the signal color used across navigation, focus states, and actions.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{themes.map(theme => <button type="button" key={theme.id} onClick={() => setAccentTheme(theme.id)} className={`flex items-center gap-2 p-3 rounded-xl border text-left transition ${accentTheme === theme.id ? 'border-accent bg-white/10' : 'border-white/10 hover:border-white/25'}`}><span className="w-4 h-4 rounded-full" style={{ backgroundColor: theme.color, boxShadow: `0 0 14px ${theme.color}66` }} /> <span className="text-xs font-semibold flex-1">{theme.label}</span>{accentTheme === theme.id && <Check className="w-4 h-4 text-accent" />}</button>)}</div></section>
    <section className="glass-strong p-5 rounded-2xl"><div className="flex items-center justify-between gap-4"><div><h3 className="text-sm font-bold flex items-center gap-2"><EyeOff className="w-4 h-4 text-accent" />Forensic report PII masking</h3><p className="text-xs text-slate-400 mt-1 leading-5">Redact card numbers, phone numbers, and email usernames in exported PDFs.</p></div><label className="relative inline-flex items-center cursor-pointer"><input type="checkbox" checked={maskPii} onChange={e => setMaskPii(e.target.checked)} className="sr-only peer" /><span className="w-11 h-6 rounded-full bg-slate-700 peer-checked:bg-accent after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full" /></label></div></section>
    <div className="p-4 rounded-2xl bg-accent/5 border border-accent/20 text-xs text-slate-400 space-y-1"><div className="text-accent font-semibold flex items-center gap-1.5"><Lock className="w-3.5 h-3.5" />FIPS 180-4 cryptographic integrity guarantee</div><p>All purge and update actions append an immutable block to the Evidence Vault hash-chain.</p></div>
  </div>;
}
